// Hello world

/*
  A class is a blueprint that defines the variables and the methods common to
  all objects of a certain kind

  Bytecode is a machine-independent code generated by the Java compiler and
  executed by the interpreter

  Compiler: javac MyClass.java
  Interpreter: java MyClass (bytecode)

  Running a single-file program in one line
  java MyClass.java

  The anatomy of a class
  The main() method
*/

public class Hello {
  public static void main(String[] args) {
    System.out.println("Hello world");
  }
}
